---
abstract: 'Show just the keys of deep data structure'
author:
  - 'Mateu X Hunter <hunter@missoula.org>'
build_requires:
  CGI: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  IO::Handle: 0
  Test::More: 0
  perl: 5.006
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Skeleton
requires:
  Data::Dumper::Concise: 0
  Moo: 0
  MooX::Types::MooseLike::Base: 0
  Scalar::Util: 0
  diagnostics: 0
  strictures: 1
version: 0.03
